version: '3.8'
services:
  mongo:
    image: mongo:4.4.18
    restart: always
    container_name: mongodb
    ports:
      - '127.0.0.1:27017:27017'
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
      MONGO_INITDB_DATABASE: media
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  warp_beacon:
    restart: always
    build: ./docker_app
    env_file:
      - 'variables.env'
    volumes:
      - /var/warp_beacon:/var/warp_beacon
      - ./warp_beacon:/app
